package GUI;
import OOP.Finance;
import OOP.SessionTimeoutManager;
import OOP.SystemIT;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public final class PayslipPopup extends javax.swing.JFrame {
    
    /**
     * Creates new form PayslipPopup
     */
    private String employeeID;
    
    public PayslipPopup(String employeeID){
        initComponents();
        this.employeeID = employeeID;
        empNumDisplay.setText(employeeID);
        populatePayslipFields();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
                        //Call timeout
        SessionTimeoutManager.start(this, () -> {
        // This runs on Swing EDT — safe to show dialogs and dispose
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Session timed out due to inactivity.",
                "Session Expired",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            new GUI.LogIn().setVisible(true); // Assuming Login is in GUI package
            this.dispose();
        });
    }
        @Override
    public void dispose() {
        SessionTimeoutManager.stop(); // Explicit cleanup
        super.dispose();
    }

    private PayslipPopup() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        empNumDisplay = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        empNumDisplay1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        welcomeBack1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        empIbigNum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        empSSSNum = new javax.swing.JTextField();
        empTINNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        empPhilHealthNum = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        welcomeBack3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        empRiceSubsidyNum = new javax.swing.JTextField();
        empBasicSalaryNum = new javax.swing.JTextField();
        empClothingAllowanceNum = new javax.swing.JTextField();
        empPhoneAllowanceNum = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        empSemiMonthlyNum = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        empHourlyRateNum = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        totalPayout = new javax.swing.JLabel();
        welcomeBack5 = new javax.swing.JLabel();
        welcomeBack2 = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setText("ID:");

        empNumDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNumDisplayActionPerformed(evt);
            }
        });

        jLabel3.setText("Name:");

        empNumDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNumDisplay1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empNumDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empNumDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(empNumDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(empNumDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        welcomeBack1.setBackground(new java.awt.Color(255, 255, 255));
        welcomeBack1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeBack1.setText("Deductions");

        jLabel4.setText("Pag-IBIG:");

        empIbigNum.setEditable(false);
        empIbigNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIbigNumActionPerformed(evt);
            }
        });

        jLabel5.setText("SSS:");

        empSSSNum.setEditable(false);
        empSSSNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empSSSNumActionPerformed(evt);
            }
        });

        empTINNum.setEditable(false);
        empTINNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empTINNumActionPerformed(evt);
            }
        });

        jLabel6.setText("TIN:");

        jLabel7.setText("PhilHealth:");

        empPhilHealthNum.setEditable(false);
        empPhilHealthNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPhilHealthNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empSSSNum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empIbigNum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empPhilHealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empTINNum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(welcomeBack1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(empIbigNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(empSSSNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(empTINNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(empPhilHealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        welcomeBack3.setBackground(new java.awt.Color(255, 255, 255));
        welcomeBack3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeBack3.setText("Benefits");

        jLabel10.setText("Phone Allowance:");

        empRiceSubsidyNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empRiceSubsidyNumActionPerformed(evt);
            }
        });

        empBasicSalaryNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empBasicSalaryNumActionPerformed(evt);
            }
        });

        empClothingAllowanceNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empClothingAllowanceNumActionPerformed(evt);
            }
        });

        empPhoneAllowanceNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPhoneAllowanceNumActionPerformed(evt);
            }
        });

        jLabel11.setText("Clothing Allowance:");

        jLabel8.setText("Basic Salary:");

        jLabel9.setText("Rice Subsidy: ");

        empSemiMonthlyNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empSemiMonthlyNumActionPerformed(evt);
            }
        });

        jLabel12.setText("Semi-Monthly Rate:");

        empHourlyRateNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empHourlyRateNumActionPerformed(evt);
            }
        });

        jLabel13.setText("Hourly Rate:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(welcomeBack3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empRiceSubsidyNum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empBasicSalaryNum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empClothingAllowanceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empPhoneAllowanceNum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empSemiMonthlyNum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empHourlyRateNum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(welcomeBack3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(empBasicSalaryNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(empRiceSubsidyNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(empPhoneAllowanceNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(empClothingAllowanceNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(empSemiMonthlyNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(empHourlyRateNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 124, Short.MAX_VALUE))
        );

        totalPayout.setBackground(new java.awt.Color(255, 255, 255));
        totalPayout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        totalPayout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPayout.setText("Payout #");

        welcomeBack5.setBackground(new java.awt.Color(255, 255, 255));
        welcomeBack5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        welcomeBack5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeBack5.setText("Total Salary:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeBack5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPayout, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPayout)
                    .addComponent(welcomeBack5))
                .addContainerGap())
        );

        welcomeBack2.setBackground(new java.awt.Color(255, 255, 255));
        welcomeBack2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        welcomeBack2.setForeground(new java.awt.Color(255, 255, 255));
        welcomeBack2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeBack2.setText("Employee's Payslip");

        calculateButton.setText("Pay me.");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(welcomeBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(calculateButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeBack2)
                    .addComponent(calculateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String[] getEmployeeData(String employeeID) {
    String csvFile = SystemIT.EMPLOYEE_CSV;
    String line;
    String splitBy = ",(?=([^\"]*\"[^\"]*\")*[^\"]*$)";
    try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
        // Read header
        br.readLine();
        while ((line = br.readLine()) != null) {
            String[] data = line.split(splitBy);
            //debug1
            System.out.println("Raw Data: " + Arrays.toString(data));
            if (data.length >= 19 && data[0].trim().equals(employeeID)) {
                for (int i = 0; i < data.length; i++) {
                    data[i] = data[i].replaceAll("^\"|\"$", "").trim();
                }
                //debug 2
                System.out.println("Cleaned Data: " + Arrays.toString(data));
                
                return data;
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    return null;
}

// Method to populate the fields in PayslipPopup
public void populatePayslipFields() {
    String[] row = getEmployeeData(employeeID);
    if (row == null) {
        JOptionPane.showMessageDialog(this, "Employee data not found for ID: " + employeeID, "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    empIbigNum.setText(row[6].trim());          
    empSSSNum.setText(row[3].trim());             
    empTINNum.setText(row[5].trim());            
    empPhilHealthNum.setText(row[4].trim());     
    empBasicSalaryNum.setText(row[13].trim());      
    empRiceSubsidyNum.setText(row[14].trim());      
    empPhoneAllowanceNum.setText(row[15].trim());   
    empClothingAllowanceNum.setText(row[16].trim());  
    empSemiMonthlyNum.setText(row[17].trim());      
    empHourlyRateNum.setText(row[18].trim());       
}
public void computePayroll() {
    try {
        // Remove quotes and commas from all input fields
        String basicSalaryStr = empBasicSalaryNum.getText().trim().replaceAll("[\"']", "").replace(",", "");
        String riceSubsidyStr = empRiceSubsidyNum.getText().trim().replaceAll("[\"']", "").replace(",", "");
        String phoneAllowanceStr = empPhoneAllowanceNum.getText().trim().replaceAll("[\"']", "").replace(",", "");
        String clothingAllowanceStr = empClothingAllowanceNum.getText().trim().replaceAll("[\"']", "").replace(",", "");

        // Check if any field is still empty after trimming
        if (basicSalaryStr.isEmpty() || riceSubsidyStr.isEmpty() || phoneAllowanceStr.isEmpty() || clothingAllowanceStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "One or more fields are empty! Please fill in all fields.", 
                                          "Input Error", JOptionPane.ERROR_MESSAGE);
            return;  
        }

        // Parse cleaned strings into numbers
        double basicSalary = Double.parseDouble(basicSalaryStr);
        double riceSubsidy = Double.parseDouble(riceSubsidyStr);
        double phoneAllowance = Double.parseDouble(phoneAllowanceStr);
        double clothingAllowance = Double.parseDouble(clothingAllowanceStr);

        // Compute total allowances
        double totalAllowances = riceSubsidy + phoneAllowance + clothingAllowance;

        // Apply a flat 5% deduction on the total salary (basic salary + allowances)
        double grossSalary = basicSalary + totalAllowances;
        double totalDeductions = grossSalary * 0.05;
        double netPay = grossSalary - totalDeductions;

        // Display result
        totalPayout.setText(String.format("₱%.2f", netPay));

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid number format! Ensure all fields contain valid numeric values.", 
                                      "Input Error", JOptionPane.ERROR_MESSAGE);
    }
}
    private void empNumDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNumDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNumDisplayActionPerformed

    private void empNumDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNumDisplay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNumDisplay1ActionPerformed

    private void empIbigNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIbigNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIbigNumActionPerformed

    private void empSSSNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empSSSNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empSSSNumActionPerformed

    private void empTINNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empTINNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empTINNumActionPerformed

    private void empPhilHealthNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPhilHealthNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPhilHealthNumActionPerformed

    private void empBasicSalaryNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empBasicSalaryNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empBasicSalaryNumActionPerformed

    private void empRiceSubsidyNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empRiceSubsidyNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empRiceSubsidyNumActionPerformed

    private void empPhoneAllowanceNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPhoneAllowanceNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empPhoneAllowanceNumActionPerformed

    private void empClothingAllowanceNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empClothingAllowanceNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empClothingAllowanceNumActionPerformed

    private void empSemiMonthlyNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empSemiMonthlyNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empSemiMonthlyNumActionPerformed

    private void empHourlyRateNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empHourlyRateNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empHourlyRateNumActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        computePayroll();
    }//GEN-LAST:event_calculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayslipPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayslipPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayslipPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayslipPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayslipPopup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JTextField empBasicSalaryNum;
    private javax.swing.JTextField empClothingAllowanceNum;
    private javax.swing.JTextField empHourlyRateNum;
    private javax.swing.JTextField empIbigNum;
    private javax.swing.JTextField empNumDisplay;
    private javax.swing.JTextField empNumDisplay1;
    private javax.swing.JTextField empPhilHealthNum;
    private javax.swing.JTextField empPhoneAllowanceNum;
    private javax.swing.JTextField empRiceSubsidyNum;
    private javax.swing.JTextField empSSSNum;
    private javax.swing.JTextField empSemiMonthlyNum;
    private javax.swing.JTextField empTINNum;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel totalPayout;
    private javax.swing.JLabel welcomeBack1;
    private javax.swing.JLabel welcomeBack2;
    private javax.swing.JLabel welcomeBack3;
    private javax.swing.JLabel welcomeBack5;
    // End of variables declaration//GEN-END:variables
}
